### ISSUE TITLE
《前端函数式攻城指南》第七章 129页 

### ISSUE THREAD

**Issue by 0123cf** [jcouyang/grokking-monad#1]
在129页   第三行
```
（2）同态： a.of(f).op(a.of(x)) 等于 a.of(f(x))
```
这句话里面得op单词是不是写错了 应该是ap吧（我买得是正版书）。

**Comment by jcouyang** [comment]
谢谢了,看得真仔细, 是ap没错的,typo打错了

**Comment by jcouyang** [comment]
能麻烦发到 https://github.com/jcouyang/clojure-flavored-javascript/issues 吗?
